In [2]:
# Import modules
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
# Fungsi-fungsi aktivasi
def linear(x):
  return x

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def relu(x):
  return np.maximum(0, x)

def softmax(x):
  e = np.exp(x)
  return e / np.sum(e)

activation_function = {
    "Linear": linear,
    "Sigmoid": sigmoid,
    "ReLU": relu,
    "Softmax": softmax,
}

In [106]:
class Layer():
  def __init__(self, weight, bias, activation):
    if activation not in ['Linear', 'Sigmoid', 'ReLU', 'Softmax']:
          raise NotImplementedError("Layer activation `%s` is not implemented." 
                                      % activation)
    self.weight = weight
    self.bias = bias
    self.activation = activation

  def forward_propagation(self, input):
    result = np.dot(input , self.weight) + self.bias
    return activation_function[self.activation](result)

class NeuralNetwork():
  def __init__(self):
    self.layers = []
  
  def summary(self):
    print("Jumlah layer: ", len(self.layers))
    for i, layer in enumerate(self.layers):
      print("============================================================")
      print('Layer {} (Activation: "{}", Units: {})'
      .format(i+1, layer.activation, len(layer.weight)))
      
      print("Weight:")
      print(np.array(layer.weight))
      
      print("Bias:")
      print(np.array(layer.bias))
    print("============================================================")

  def add(self, layer):
    self.layers.append(layer)
  
  def predict(self, input):
    h = input
    for layer in (self.layers):
        h = layer.forward_propagation(input)
    print(h)
        
#   def abaikan(self, input):
#     h = input
#     for layer in (self.layers):
#         print("h awal: ",h)
#         h = layer.forward_propagation(input)
#         print("weight:", layer.weight)
#         print("bias:", layer.bias)
#         print("activation:", layer.activation)
#         print("fungsi aktivasi: ", layer.forward_propagation(input))
#         print("h akhir: ", h)
#         print("------------------------------")
        

  def load_file(self, filename):
    '''
    File format
    <depth>
    <units> <activation function>
    <weight0> 
    <bias0>
    '''
    with open(filename, 'r') as file:
      depth = int(file.readline().strip())
      for i in range (depth):
        line = file.readline().strip().split()
        unit = int(line[0])
        activation = line[1]

        # Weight Matrice
        weight = []
        for j in range(unit):
          weight.append(list(map(float, file.readline().strip().split())))

        # Bias Matrice
        bias = list(map(float, file.readline().strip().split()))
        

        # Add layer
        layer = Layer(weight, bias, activation)
        self.add(layer)
      
      # End of file
    # Close file

In [107]:
# XOR Sigmoid Model dan XOR Relu-Linear Model
model = NeuralNetwork()
filename = 'xor_sigmoid.txt'
model.load_file(filename)

In [108]:
model.summary()

Jumlah layer:  2
Layer 1 (Activation: "Sigmoid", Units: 2)
Weight:
[[ 20.  20.]
 [-20. -20.]]
Bias:
[-10.  30.]
Layer 2 (Activation: "Sigmoid", Units: 1)
Weight:
[[20. 20.]]
Bias:
[-30.]


In [114]:
model.predict(1)

[[4.53978687e-05 4.53978687e-05]]
