In [31]:
# Import modules
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [32]:
# Fungsi-fungsi aktivasi
def linear(x):
  return x

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def relu(x):
  return np.maximum(0, x)

def softmax(x):
  e = np.exp(x)
  return e / np.sum(e)

activation_function = {
    "Linear": linear,
    "Sigmoid": sigmoid,
    "ReLU": relu,
    "Softmax": softmax,
}

In [33]:
class Layer():
  def __init__(self, weight, bias, activation):
    if activation not in ['Linear', 'Sigmoid', 'ReLU', 'Softmax']:
          raise NotImplementedError("Layer activation `%s` is not implemented." 
                                      % activation)
    self.weight = weight
    self.bias = bias
    self.activation = activation

  def forward_propagation(self, input):
    input_T = input.T
    result = np.dot(self.weight, input_T) + self.bias
    return activation_function[self.activation](result)

class NeuralNetwork():
  def __init__(self):
    self.layers = []
  
  def summary(self):
    print("Jumlah layer: ", len(self.layers))
    for i, layer in enumerate(self.layers):
      print("============================================================")
      print('Layer {} (Activation: "{}", Units: {})'
      .format(i+1, layer.activation, len(layer.weight)))
      
      print("Weight:")
      print(np.array(layer.weight))
      
      print("Bias:")
      print(np.array(layer.bias))
    print("============================================================")

  def add(self, layer):
    self.layers.append(layer)
  
  def predict(self, input):
    arr = np.array(input)
    if arr.ndim == 1:
      instance = arr
      instance_res = instance
      for layer in self.layers:
        instance_res = layer.forward_propagation(instance_res)
      return instance_res
      
    batch = arr
    batch_res = []
    for instance in batch:
      instance_res = instance
      for layer in self.layers:
        instance_res = layer.forward_propagation(instance_res)
      
      batch_res.append(instance_res)
    
    return batch_res
        
  def load_file(self, filename):
    '''
    File format
    <depth>
    <units> <activation function>
    <weight0> 
    <bias0>
    '''
    with open(filename, 'r') as file:
      depth = int(file.readline().strip())
      for i in range (depth):
        line = file.readline().strip().split()
        unit = int(line[0])
        activation = line[1]

        # Weight Matrice
        weight = []
        for j in range(unit):
          weight.append(list(map(float, file.readline().strip().split())))

        # Bias Matrice
        bias = list(map(float, file.readline().strip().split()))
        

        # Add layer
        layer = Layer(weight, bias, activation)
        self.add(layer)
      
      # End of file
    # Close file

In [34]:
# XOR Sigmoid Model dan XOR Relu-Linear Model
model1 = NeuralNetwork()
model2 = NeuralNetwork()
filename1 = 'xor_sigmoid.txt'
filename2 = 'xor_relu_linear.txt'

data = [[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]
        
model1.load_file(filename1)
model2.load_file(filename2)

In [35]:
model1.summary()

Jumlah layer:  2
Layer 1 (Activation: "Sigmoid", Units: 2)
Weight:
[[ 20.  20.]
 [-20. -20.]]
Bias:
[-10.  30.]
Layer 2 (Activation: "Sigmoid", Units: 1)
Weight:
[[20. 20.]]
Bias:
[-30.]


In [36]:
model2.summary()

Jumlah layer:  2
Layer 1 (Activation: "ReLU", Units: 2)
Weight:
[[1. 1.]
 [1. 1.]]
Bias:
[ 0. -1.]
Layer 2 (Activation: "Linear", Units: 1)
Weight:
[[ 1. -2.]]
Bias:
[0.]


In [37]:
model1.predict(data)

[array([4.54391049e-05]),
 array([0.99995452]),
 array([0.99995452]),
 array([4.54391049e-05])]

In [38]:
model1.predict([0, 0])

array([4.54391049e-05])